language: python
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - clang-format-3.8
python:
  - "3.8"
install:
  - pushd /tmp
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.17.3/protoc-3.17.3-linux-x86_64.zip
  - unzip protoc-3.17.3-linux-x86_64.zip
  - popd
  - export PATH=/tmp/bin:$PATH
  - chmod +x ./compile_base.py
script:
  # Generates remaster_all(), base(), generate_new(), generate_files(), out_mode(cpp)...
  - ./compile_base.py -g -b -gf
  - clang-format-3.8 -i -style file $(find base -name "vbase.proto")
  - clang-format-3.8 -i -style file $(find base -name "v0.213.x_p_obf.proto")
  # - git diff --exit-code
